#!/usr/bin/env python3
"""Emit reviewed CMA/CA membership updates from StatCan table 98-10-0003-01."""

import argparse
import csv
import io
import json
import pathlib
import sys
import urllib.request
import zipfile

URL = "https://www150.statcan.gc.ca/n1/tbl/csv/98100003-eng.zip"


def download_csv() -> str:
    with urllib.request.urlopen(URL) as response:
        archive = zipfile.ZipFile(io.BytesIO(response.read()))
    names = [name for name in archive.namelist() if name.endswith(".csv") and "MetaData" not in name]
    if len(names) != 1:
        raise ValueError("expected exactly one data CSV in 98100003 archive")
    return archive.read(names[0]).decode("utf-8-sig")


def membership(csv_text: str) -> dict[str, tuple[str, str, str]]:
    rows = csv.DictReader(io.StringIO(csv_text))
    active: tuple[str, str, str] | None = None
    result: dict[str, tuple[str, str, str]] = {}
    for row in rows:
        dguid = (row.get("DGUID") or "").strip()
        name = (row.get("GEO") or row.get("GEO_NAME") or "").strip()
        if dguid.startswith("2021S0503"):
            active = (dguid, name, "cma")
        elif dguid.startswith("2021S0504"):
            active = (dguid, name, "ca")
        elif dguid.startswith("2021A0005"):
            if active is not None:
                if dguid in result:
                    raise ValueError(f"duplicate CSD membership: {dguid}")
                result[dguid] = active
        elif dguid and not dguid.startswith("2021A000"):
            raise ValueError(f"unrecognized hierarchy DGUID: {dguid}")
    return result


def sql_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--csv", type=pathlib.Path, help="already downloaded 98100003 CSV")
    parser.add_argument("--output", type=pathlib.Path, required=True)
    parser.add_argument("--overrides", type=pathlib.Path, default=pathlib.Path(__file__).with_name("location_geography_overrides.json"))
    args = parser.parse_args()
    raw = args.csv.read_text(encoding="utf-8-sig") if args.csv else download_csv()
    members = membership(raw)
    overrides = json.loads(args.overrides.read_text())
    lines = [
        "-- Generated by scripts/census/enrich_location_geographies.py; do not edit.",
        "ALTER TABLE public.census_population_2021",
        "  ADD COLUMN IF NOT EXISTS parent_area_dguid text,",
        "  ADD COLUMN IF NOT EXISTS parent_area_name text,",
        "  ADD COLUMN IF NOT EXISTS parent_area_type text;",
    ]
    for dguid, (parent_dguid, parent_name, parent_type) in sorted(members.items()):
        lines.append(
            "UPDATE public.census_population_2021 SET "
            f"parent_area_dguid = {sql_literal(parent_dguid)}, parent_area_name = {sql_literal(parent_name)}, "
            f"parent_area_type = {sql_literal(parent_type)}, is_cma_component = {str(parent_type == 'cma').lower()} "
            f"WHERE dguid = {sql_literal(dguid)};"
        )
    for bucket, patch in sorted(overrides.items()):
        assignments = ", ".join(f"{key} = {sql_literal(value)}" if isinstance(value, str) else f"{key} = {str(value).lower()}" for key, value in patch.items())
        lines.append(f"UPDATE public.census_population_2021 SET {assignments} WHERE bucket = {sql_literal(bucket)};")
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
